CANTIDAD_VERTICAL_TILES = 11
TILE_SIZE = 64
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = CANTIDAD_VERTICAL_TILES * TILE_SIZE
FPS = 60

ANCHO_PERSONAJE = 60
ALTO_PERSONAJE = 60

VELOCIDAD_PROYECTIL_JUGADOR = 500
VELOCIDAD_PROYECTIL_ENEMIGO = 300

VELOCIDAD_JUGADOR = 1550 # 550
VELOCIDAD_ENEMIGOS = 250
POTENCIA_SALTO = -500
GRAVEDAD = 55

VIDA_BASE_JUGADOR = 3
ATAQUE_BASE_JUGADOR = 1

UMBRAL_SSJ = 6

VIDA_SSJ_JUGADOR = 5
ATAQUE_SSJ_JUGADOR = 2

VIDA_BASE_ENEMIGOS = 2


VELOCIDAD_ANIMACION = 9
VELOCIDAD_ANIMACION_MUERTE = 7
VELOCIDAD_ANIMACION_MUERTE_ENEMIGOS = 6

TIEMPO_DISPARO_ENEMIGO = 2 #(segundos) entre cada rafaga
ESPERA_ENTRE_DISPAROS = 0.2 #(segundos), espera entre cada disparo de la rafaga
DISPAROS_ENEMIGOS = 2 #disparos en la rafaga

TIEMPO_DISPARO_JUGADOR = 0.25

TIEMPO_LASER = 2

#--- jefe

VIDA_JEFE = 40

VELOCIDAD_ANIMACION_Y_DISPARO_JEFE = 1

TIEMPO_CARGA_ATAQUE_JEFE = 1
DURACION_ATAQUE_JEFE = 1

UMBRAL_GENKI_DAMA = 24